name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "**.rs"
      - "**Cargo.**"
      - ".github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  build:
    strategy:
      matrix:
        rust_channel: [stable, beta, nightly]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_channel }}
          override: true
          # components: llvm-tools-preview

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
          # tool: cargo-llvm-cov,cargo-nextest

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-rust_${{ matrix.rust_channel }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose --all-targets --all --all-features

      - name: Test
        run: cargo nextest run --all-features --all

      # - name: cargo llvm-cov
      #   run: |
      #     cargo llvm-cov --locked --all --all-features --lcov --output-path lcov.info

      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #     fail_ci_if_error: true
